apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"filebrowser","namespace":"filebrowser"},"spec":{"ports":[{"port":80,"targetPort":8080}],"selector":{"app":"filebrowser"}}}
  creationTimestamp: "2026-01-10T20:32:50Z"
  name: filebrowser
  namespace: filebrowser
  resourceVersion: "5680570"
  uid: b2b4e3d2-0667-412c-934b-8e65985981d4
spec:
  clusterIP: 10.102.12.33
  clusterIPs:
  - 10.102.12.33
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
  selector:
    app: filebrowser
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
