all:
  vars:
    ansible_user: ubuntu
    ansible_ssh_private_key_file: ~/.ssh/id_ed25519
    ansible_python_interpreter: /usr/bin/python3
docker:
  hosts:
    docker-host:
      ansible_host: 10.10.0.204
k8s_control:
  hosts:
    k8s-cp01:
      ansible_host: 10.10.0.103
k8s_workers:
  hosts:
    k8s-worker01:
      ansible_host: 10.10.0.104
    k8s-worker02:
      ansible_host: 10.10.0.105
k8s_all:
  children:
    k8s_control:
    k8s_workers:
```

Save and exit (Ctrl+O, Enter, Ctrl+X).

Then install Ansible:
```
sudo apt update && sudo apt install ansible -y
