all:
  vars:
    ansible_user: platformadmin
    ansible_ssh_private_key_file: ~/.ssh/id_ed25519
    ansible_python_interpreter: /usr/bin/python3

docker:
  hosts:
    docker-host:
      ansible_host: 192.168.1.204

k8s_control:
  hosts:
    k8s-cp01:
      ansible_host: 192.168.1.41

k8s_workers:
  hosts:
    k8s-worker01:
      ansible_host: 192.168.1.175
    k8s-worker02:
      ansible_host: 192.168.1.80

k8s_all:
  children:
    k8s_control:
    k8s_workers:
