apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      auth.istio.io/8089: NONE
    creationTimestamp: "2026-01-10T02:53:13Z"
    generateName: cm-acme-http-solver-
    labels:
      acme.cert-manager.io/http-domain: "2974288837"
      acme.cert-manager.io/http-token: "1067322972"
      acme.cert-manager.io/http01-solver: "true"
    name: cm-acme-http-solver-hfz8z
    namespace: url-shortener
    ownerReferences:
    - apiVersion: acme.cert-manager.io/v1
      blockOwnerDeletion: true
      controller: true
      kind: Challenge
      name: short-alphonzojonesjr-com-tls-1-1728084244-1308168110
      uid: 89c69a7b-0024-451e-88ac-fe60feba2d0d
    resourceVersion: "5467024"
    uid: c91dfaf7-e5f4-40ee-966a-d9962318922e
  spec:
    clusterIP: 10.111.41.100
    clusterIPs:
    - 10.111.41.100
    externalTrafficPolicy: Cluster
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - name: http
      nodePort: 31966
      port: 8089
      protocol: TCP
      targetPort: 8089
    selector:
      acme.cert-manager.io/http-domain: "2974288837"
      acme.cert-manager.io/http-token: "1067322972"
      acme.cert-manager.io/http01-solver: "true"
    sessionAffinity: None
    type: NodePort
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      argocd.argoproj.io/tracking-id: url-shortener:/Service:url-shortener/postgres
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{"argocd.argoproj.io/tracking-id":"url-shortener:/Service:url-shortener/postgres"},"name":"postgres","namespace":"url-shortener"},"spec":{"ports":[{"port":5432}],"selector":{"app":"postgres"}}}
    creationTimestamp: "2025-12-28T08:01:43Z"
    name: postgres
    namespace: url-shortener
    resourceVersion: "1079859"
    uid: b38c0d95-c7f6-4034-9d07-b06032a7e8e3
  spec:
    clusterIP: 10.109.20.254
    clusterIPs:
    - 10.109.20.254
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - port: 5432
      protocol: TCP
      targetPort: 5432
    selector:
      app: postgres
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"url-shortener","namespace":"url-shortener"},"spec":{"ports":[{"port":80,"targetPort":8000}],"selector":{"app":"url-shortener"}}}
    creationTimestamp: "2025-12-28T08:01:43Z"
    name: url-shortener
    namespace: url-shortener
    resourceVersion: "4974771"
    uid: a494fd07-6bc3-4468-a92d-dd3182c0d99b
  spec:
    clusterIP: 10.103.73.225
    clusterIPs:
    - 10.103.73.225
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - port: 80
      protocol: TCP
      targetPort: 8000
    selector:
      app: url-shortener
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
- apiVersion: v1
  kind: Service
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"url-shortener-minimal","namespace":"url-shortener"},"spec":{"ports":[{"port":80,"targetPort":80}],"selector":{"app":"url-shortener-minimal"}}}
    creationTimestamp: "2026-01-07T03:40:02Z"
    name: url-shortener-minimal
    namespace: url-shortener
    resourceVersion: "4735669"
    uid: 9b4f6bd6-9f2c-4758-ad32-f6d72a8dfe19
  spec:
    clusterIP: 10.109.208.217
    clusterIPs:
    - 10.109.208.217
    internalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - port: 80
      protocol: TCP
      targetPort: 80
    selector:
      app: url-shortener-minimal
    sessionAffinity: None
    type: ClusterIP
  status:
    loadBalancer: {}
kind: List
metadata:
  resourceVersion: ""
