apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"networking.k8s.io/v1","kind":"Ingress","metadata":{"annotations":{},"name":"cluster-health-api","namespace":"cluster-api"},"spec":{"ingressClassName":"nginx","rules":[{"host":"api.alphonzojonesjr.com","http":{"paths":[{"backend":{"service":{"name":"cluster-health-api","port":{"number":80}}},"path":"/","pathType":"Prefix"}]}}]}}
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
  creationTimestamp: "2026-01-11T01:56:40Z"
  generation: 2
  name: cluster-health-api
  namespace: cluster-api
  resourceVersion: "9284463"
  uid: 330a9235-110f-46a2-9668-76ade4574625
spec:
  ingressClassName: nginx
  rules:
  - host: api.alphonzojonesjr.com
    http:
      paths:
      - backend:
          service:
            name: cluster-health-api
            port:
              number: 80
        path: /
        pathType: Prefix
  tls:
  - hosts:
    - api.alphonzojonesjr.com
    secretName: api-alphonzojonesjr-com-tls
status:
  loadBalancer:
    ingress:
    - ip: 10.10.0.115
