apiVersion: v1
kind: Service
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"chatbot","namespace":"chatbot"},"spec":{"ports":[{"port":80,"protocol":"TCP","targetPort":8000}],"selector":{"app":"chatbot"},"type":"ClusterIP"}}
  creationTimestamp: "2025-12-28T08:21:05Z"
  name: chatbot
  namespace: chatbot
  resourceVersion: "5443286"
  uid: 5570cd87-e62e-4545-8a1b-5d3df831f1c1
spec:
  clusterIP: 10.106.154.252
  clusterIPs:
  - 10.106.154.252
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8000
  selector:
    app: chatbot
  sessionAffinity: None
  type: ClusterIP
status:
  loadBalancer: {}
