apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: technitium
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Newbigfonsz/platform-engineering-lab.git
    targetRevision: HEAD
    path: apps/technitium
  destination:
    server: https://kubernetes.default.svc
    namespace: technitium
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
