apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "12"
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"apps/v1","kind":"Deployment","metadata":{"annotations":{},"name":"portfolio","namespace":"portfolio"},"spec":{"replicas":2,"selector":{"matchLabels":{"app":"portfolio"}},"template":{"metadata":{"labels":{"app":"portfolio"}},"spec":{"containers":[{"image":"nginx:alpine","name":"portfolio","ports":[{"containerPort":80}],"volumeMounts":[{"mountPath":"/usr/share/nginx/html","name":"html"}]}],"volumes":[{"configMap":{"name":"portfolio-html"},"name":"html"}]}}}}
  creationTimestamp: "2025-12-26T03:30:14Z"
  generation: 16
  name: portfolio
  namespace: portfolio
  resourceVersion: "5687188"
  uid: c9e2c6a1-6618-4f79-a2a6-e07fbadfd727
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: portfolio
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/restartedAt: "2026-01-10T21:06:05Z"
      creationTimestamp: null
      labels:
        app: portfolio
    spec:
      containers:
      - image: nginx:alpine
        imagePullPolicy: IfNotPresent
        name: portfolio
        ports:
        - containerPort: 80
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: html
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
      volumes:
      - configMap:
          defaultMode: 420
          name: portfolio-html
        name: html
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2026-01-08T02:59:44Z"
    lastUpdateTime: "2026-01-08T02:59:44Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2025-12-28T06:47:06Z"
    lastUpdateTime: "2026-01-10T21:06:08Z"
    message: ReplicaSet "portfolio-bbf87467b" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 16
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
