apiVersion: apps/v1
kind: Deployment
metadata:
  name: vanmenh
  namespace: vanmenh
spec:
  replicas: 2
  selector:
    matchLabels:
      app: vanmenh
  template:
    metadata:
      labels:
        app: vanmenh
    spec:
      containers:
      - name: vanmenh
        image: aljonesjr/vanmenh:v6-premium
        ports:
        - containerPort: 80
