apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vanmenh
  namespace: vanmenh
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/limit-rps: "10"
    nginx.ingress.kubernetes.io/limit-burst-multiplier: "5"
    nginx.ingress.kubernetes.io/from-to-www-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - vanmenhapp.com
        - www.vanmenhapp.com
      secretName: vanmenhapp-tls
  rules:
    - host: vanmenhapp.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: vanmenh
                port:
                  number: 80
    - host: www.vanmenhapp.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: vanmenh
                port:
                  number: 80
