apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: vanmenh
  namespace: vanmenh
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - vanmenh.alphonzojonesjr.com
    secretName: vanmenh-tls
  rules:
  - host: vanmenh.alphonzojonesjr.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: vanmenh
            port:
              number: 80
