apiVersion: v1
kind: Service
metadata:
  annotations:
      {"apiVersion":"v1","kind":"Service","metadata":{"annotations":{},"name":"vanmenh","namespace":"vanmenh"},"spec":{"ports":[{"port":80,"targetPort":80}],"selector":{"app":"vanmenh"}}}
  name: vanmenh
  namespace: vanmenh
spec:
  - 10.106.59.76
  internalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: vanmenh
  sessionAffinity: None
  type: ClusterIP
  loadBalancer: {}
